# Generated by Django 2.2.24 on 2021-11-10 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0003_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='title',
            field=models.CharField(max_length=200, verbose_name='投票選項'),
        ),
    ]
